POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email" : "test2@email.com",
    "password": "test2",
    "admin":"true"
}


### Find a perticular user with a given id

Get http://localhost:3000/auth/2


### Find all users with a given email
Get http://localhost:3000/auth?email=test2@email.com


### Delete a user with a given id

DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "password": "aaa"
}